name: action di ferrarini #github action dice che ci deve essere una top level key name
on:  # dizionario con chiave push
  push: # una qualsiasi azione di push attiva questa action
jobs: 
  ciao:
    runs-on: ubuntu-latest # qui vuole il sistema operativo
    steps: #lista di comandi
      - run: echo "sudo shutdown"
      - run: python --version
      - run: pip --version
      - run: lsb_release -d
      